name: CI

on: [push]
jobs: 
  job1: 
  
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: test checkout
       run: echo Hellooooooooooooooooooooooooooooooooooooo 
   
  job2:
    runs-on: windows-latest 
    steps:
     - name: Setup Node.js environment
       uses: actions/setup-node@v3.6.0
     - name: Checkout code
       uses: actions/checkout@v3
     - name: npm install
       run:  npm install
     - name: Run Jest
       uses: jlndk/github-action-jest@1.0.3
 

     

     
    
      
     
